services:

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile

    image: local/order-service-web:1.0.0
    container_name: order_service_web

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: "5432"
      MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"

    ports:
      - "127.0.0.1:8000:8000"

    volumes:
      - order_service_static:/app/staticfiles
      - order_service_media:/app/order_service/media

    networks:
      - order_service_db
      - order_service_front


  nginx:
    image: nginx:1.27-alpine
    container_name: order_service_nginx

    restart: unless-stopped

    depends_on:
      - web

    ports:
      - "80:80"

    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - order_service_static:/app/staticfiles:ro
      - order_service_media:/app/order_service/media:ro

    networks:
      - order_service_front


networks:

  order_service_db:
    external: true
    name: postgres_default

  order_service_front:


volumes:

  order_service_static:
  order_service_media:
