services:
  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile

    image: local/order-service-web:1.0.0
    container_name: order_service_web

    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: "5432"
      MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"

    ports:
      - "127.0.0.1:8000:8000"

    volumes:
      - order_service_static:/app/staticfiles
      - order_service_media:/app/media

    networks:
      - order_service_db

networks:
  order_service_db:
    external: true
    name: postgres_default

volumes:
  order_service_static:
  order_service_media: