"""
Django settings for order_service project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from pymongo import MongoClient
import os


from dotenv import load_dotenv

ONEC_ODATA_BASE_URL = os.getenv(
    "ONEC_ODATA_BASE_URL",
    "http://10.10.2.107/inter_trade11/ru/odata/standard.odata",
)

ONEC_ODATA_USER = os.getenv("ONEC_ODATA_USER", "")
ONEC_ODATA_PASSWORD = os.getenv("ONEC_ODATA_PASSWORD", "")

ONEC_ODATA_TIMEOUT = int(
    os.getenv("ONEC_ODATA_TIMEOUT", "60")
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR.parent / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in {
    "1",
    "true",
    "yes",
    "on",
}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv(
        "DJANGO_ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'orders',
    'catalog',
    'sales',
    'mssql'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'catalog.middleware.BrandContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'order_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'catalog.context_processors.brand_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'order_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ["POSTGRES_USER"],
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],
        "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
        "CONN_MAX_AGE": 60,
    },
    "mssql": {
        "ENGINE": "mssql",
        "NAME": os.environ["MSSQL_DB"],
        "USER": os.environ["MSSQL_USER"],
        "PASSWORD": os.environ["MSSQL_PASSWORD"],
        "HOST": os.environ["MSSQL_HOST"],
        "PORT": os.getenv("MSSQL_PORT", "1433"),
        "OPTIONS": {
            "driver": os.getenv(
                "MSSQL_DRIVER",
                "ODBC Driver 17 for SQL Server",
            ),
        },
    },
}

MONGO_CLIENT = MongoClient('mongodb://admin_zo:Olegpellich1!@10.10.2.106:27017/')
MONGO_DB = MONGO_CLIENT['sales_order']

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

LOGIN_REDIRECT_URL = '/orders/'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage.FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Раделяем по брендам

BRAND_GUINOT_ID = (
    "e3154c7c-4423-11e9-8120-a21e6608e067"
)

BRAND_RHEA_ID = (
    "e3154c7d-4423-11e9-8120-a21e6608e067"
)


BRAND_SITES = {
    os.getenv(
        "GUINOT_DOMAIN",
        "guinot.local",
    ).lower(): {
        "code": "guinot",
        "brand_id": BRAND_GUINOT_ID,
        "title": "Guinot",
        "theme": "guinot",
    },

    os.getenv(
        "RHEA_DOMAIN",
        "rhea.local",
    ).lower(): {
        "code": "rhea",
        "brand_id": BRAND_RHEA_ID,
        "title": "Rhea Cosmetics",
        "theme": "rhea",
    },
}


# Для текущей разработки через inter-oleg04.
# Позже в production можно убрать.
DEFAULT_BRAND_ID = os.getenv(
    "DEFAULT_BRAND_ID",
    BRAND_GUINOT_ID,
)
