# Generated by Django 5.0.10 on 2026-08-10 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_remove_contract_unique_legal_entity_contract_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Номер')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Черновик'), (2, 'На согласовании'), (3, 'Оформлен'), (4, 'Отгрузка'), (5, 'Завершен')], default=1, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('cashless', 'Безналичная оплата')], max_length=20, verbose_name='Форма оплаты')),
                ('shipping_type', models.CharField(max_length=100, verbose_name='Способ отгрузки')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка, %')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('sent_to_1c_at', models.DateTimeField(blank=True, null=True, verbose_name='Передан в 1С')),
                ('one_c_order_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Идентификатор заказа в 1С')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.contract', verbose_name='Договор')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.legalentity', verbose_name='Клиент')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.legalentitydeliveryaddress', verbose_name='Адрес доставки')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catalog.pricetype', verbose_name='Тип цен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(verbose_name='Номер строки')),
                ('product_name', models.CharField(max_length=500, verbose_name='Название товара')),
                ('article', models.CharField(blank=True, max_length=255, verbose_name='Артикул')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка, %')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
                'ordering': ('line_number',),
            },
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'line_number'), name='unique_order_line_number'),
        ),
    ]
