# Generated by Django 5.0.10 on 2026-08-31 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_order_shipping_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_working_days', models.PositiveSmallIntegerField(default=3, verbose_name='Рабочих дней до доставки')),
                ('delivery_cutoff_time', models.TimeField(default=datetime.time(13, 0), help_text='Заказы после этого времени считаются принятыми следующим рабочим днём.', verbose_name='Время отсечения для доставки')),
                ('pickup_same_day_enabled', models.BooleanField(default=True, verbose_name='Разрешать самовывоз в день заказа')),
                ('pickup_same_day_cutoff', models.TimeField(default=datetime.time(13, 0), help_text='После этого времени самовывоз доступен со следующего рабочего дня.', verbose_name='Время отсечения для самовывоза')),
                ('booking_horizon_days', models.PositiveSmallIntegerField(default=60, verbose_name='Горизонт выбора даты, дней')),
            ],
            options={
                'verbose_name': 'Настройка отгрузки',
                'verbose_name_plural': 'Настройки отгрузки',
            },
        ),
        migrations.CreateModel(
            name='WorkCalendarException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('day_type', models.CharField(choices=[('working', 'Рабочий день'), ('non_working', 'Нерабочий день')], max_length=20, verbose_name='Тип дня')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Исключение производственного календаря',
                'verbose_name_plural': 'Исключения производственного календаря',
                'ordering': ('date',),
            },
        ),
    ]
