# Generated by Django 5.0.10 on 2026-09-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_shippingsettings_workcalendarexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_promo_gift',
            field=models.BooleanField(default=False, verbose_name='Подарок'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_promo_product',
            field=models.BooleanField(default=False, verbose_name='Товар промоакции'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promo_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Промоакция'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promo_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название промоакции'),
        ),
    ]
