# Generated by Django 5.0.10 on 2026-09-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_orderitem_is_promo_gift_orderitem_is_promo_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Текущий шаг оформления'),
        ),
    ]
