# Generated by Django 5.0.10 on 2026-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_order_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name_translation',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Перевод названия товара'),
        ),
    ]
