# Generated by Django 5.0.10 on 2026-09-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_orderitem_product_name_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Транспортная компания',
                'verbose_name_plural': 'Транспортные компании',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='transport_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.transportcompany', verbose_name='Транспортная компания'),
        ),
    ]
