# Generated by Django 5.0.10 on 2026-09-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_transportcompany_order_transport_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportcompany',
            name='id_1c',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='Идентификатор 1С'),
        ),
    ]
