# Generated by Django 5.0.10 on 2026-09-17 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_transportcompany_id_1c'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='one_c_order_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа в 1С'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Номер заказа 1С'),
        ),
        migrations.AlterField(
            model_name='order',
            name='one_c_order_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Идентификатор заказа в 1С'),
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время')),
                ('event_type', models.CharField(choices=[('created', 'Создание черновика'), ('confirm_started', 'Начало оформления'), ('1c_request', 'Передача в 1С'), ('1c_success', 'Заказ создан в 1С'), ('1c_error', 'Ошибка передачи в 1С'), ('status_changed', 'Изменение статуса')], db_index=True, max_length=50, verbose_name='Событие')),
                ('level', models.CharField(choices=[('info', 'Информация'), ('success', 'Успешно'), ('warning', 'Предупреждение'), ('error', 'Ошибка')], default='info', max_length=20, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sales.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие заказа',
                'verbose_name_plural': 'Журнал заказа',
                'ordering': ['-created_at'],
            },
        ),
    ]
