# Generated by Django 5.0.10 on 2026-07-17 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('legal_entity_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор клиента в 1С')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Полное наименование')),
                ('client_type', models.CharField(choices=[('llc', 'ООО'), ('ie', 'ИП'), ('person', 'Физическое лицо')], max_length=20, verbose_name='Тип клиента')),
                ('inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PriceType',
            fields=[
                ('price_type_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор типа цен в 1С')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование типа цен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип цен',
                'verbose_name_plural': 'Типы цен',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('article', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=500)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PromoAction',
            fields=[
                ('promo_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Промо акция',
                'verbose_name_plural': 'Промо акции',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=255, verbose_name='Идентификатор договора в 1С')),
                ('contract_name', models.CharField(max_length=500, verbose_name='Наименование договора')),
                ('brand', models.CharField(choices=[('e3154c7c-4423-11e9-8120-a21e6608e067', 'Guinot'), ('e3154c7d-4423-11e9-8120-a21e6608e067', 'Rhea cosmetics')], max_length=50, verbose_name='Бренд')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='catalog.legalentity', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ('contract_name',),
            },
        ),
        migrations.CreateModel(
            name='LegalEntityDeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор адреса в 1С')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='catalog.legalentity', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ('address',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='catalog.pricetype', verbose_name='Тип цен')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='UserLegalEntityAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка, %')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accesses', to='catalog.legalentity', verbose_name='Клиент')),
                ('price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities', to='catalog.pricetype', verbose_name='Тип цен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ пользователя к клиенту',
                'verbose_name_plural': 'Доступы пользователей к клиентам',
            },
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'contract_id'), name='unique_legal_entity_contract'),
        ),
        migrations.AddConstraint(
            model_name='legalentitydeliveryaddress',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'address_id'), name='unique_legal_entity_delivery_address'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('product', 'price_type'), name='unique_product_price_type'),
        ),
        migrations.AddConstraint(
            model_name='userlegalentityaccess',
            constraint=models.UniqueConstraint(fields=('user', 'legal_entity'), name='unique_user_legal_entity'),
        ),
    ]
