# Generated by Django 5.0.10 on 2026-07-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор бренда в 1С')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_actions', to='catalog.brand', verbose_name='Бренд'),
        ),
    ]
