# Generated by Django 5.0.10 on 2026-07-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_customer_selectable',
            field=models.BooleanField(db_index=True, default=False, help_text='Управляется приложением. При повторной синхронизации Airflow значение не изменяется.', verbose_name='Доступен для выбора клиентом'),
        ),
        migrations.AddField(
            model_name='product',
            name='level_2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Уровень иерархии 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='level_3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Уровень иерархии 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='level_4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Уровень иерархии 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_translation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Перевод наименования'),
        ),
        migrations.AddField(
            model_name='product',
            name='source_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Исходное наименование из 1С'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
    ]
