# Generated by Django 5.0.10 on 2026-08-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_category_product_is_customer_selectable_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contract',
            name='unique_legal_entity_contract',
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'brand'), name='unique_legal_entity_brand_contract'),
        ),
    ]
