# Generated by Django 5.0.10 on 2026-08-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_contract_unique_legal_entity_contract_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(db_index=True, default='YE', max_length=10, verbose_name='Валюта')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Курс к рублю')),
                ('valid_from', models.DateField(db_index=True, verbose_name='Действует с')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ('-valid_from', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='currencyrate',
            constraint=models.UniqueConstraint(fields=('currency_code', 'valid_from'), name='unique_currency_rate_date'),
        ),
    ]
