# Generated by Django 5.0.10 on 2026-08-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_currencyrate_currencyrate_unique_currency_rate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор склада в 1С')),
                ('organization_id', models.CharField(db_index=True, max_length=255, verbose_name='Организация в 1С')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование склада')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ('organization_id', 'name'),
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, help_text='UID организации из 1С. Используется для определения складов и остатков по договору.', max_length=255, null=True, verbose_name='Организация в 1С'),
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='Остаток')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='catalog.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_balances', to='catalog.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Остаток товара',
                'verbose_name_plural': 'Остатки товаров',
                'indexes': [models.Index(fields=['warehouse', 'product'], name='stock_warehouse_product_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='unique_product_warehouse_stock'),
        ),
    ]
