# Generated by Django 5.0.10 on 2026-08-18 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_warehouse_contract_organization_id_stockbalance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoaction',
            options={'ordering': ('priority', '-valid_from', 'name'), 'verbose_name': 'Промо акция', 'verbose_name_plural': 'Промо акции'},
        ),
        migrations.RemoveField(
            model_name='promoaction',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='promoaction',
            name='date_to',
        ),
        migrations.AddField(
            model_name='promoaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promoaction',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Используется для скидочных акций. Не суммируется со скидкой клиента.', max_digits=5, null=True, verbose_name='Промо-скидка, %'),
        ),
        migrations.AddField(
            model_name='promoaction',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное изображение карточки акции.', null=True, upload_to='promo/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='promoaction',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='Чем меньше значение, тем выше приоритет акции при пересечении условий.', verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='promoaction',
            name='promo_type',
            field=models.CharField(choices=[('buy_x_get_y', 'Купи X — получи Y'), ('bundle_gift', 'Набор товаров + подарок'), ('bundle_discount', 'Скидка на набор товаров')], db_index=True, default='bundle_discount', max_length=30, verbose_name='Тип акции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promoaction',
            name='short_description',
            field=models.CharField(blank=True, help_text='Отображается на карточке акции.', max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='promoaction',
            name='show_progress',
            field=models.BooleanField(default=False, help_text='Если включено, клиент увидит, каких товаров не хватает до выполнения условий акции.', verbose_name='Показывать прогресс выполнения'),
        ),
        migrations.AddField(
            model_name='promoaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AddField(
            model_name='promoaction',
            name='valid_from',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Действует с'),
        ),
        migrations.AddField(
            model_name='promoaction',
            name='valid_to',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Действует до'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Отображается в окне «Подробнее».', verbose_name='Подробное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название акции'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='promo_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор акции'),
        ),
        migrations.CreateModel(
            name='PromoActionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Необходимое количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_conditions', to='catalog.product', verbose_name='Товар')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_products', to='catalog.promoaction', verbose_name='Промо акция')),
            ],
            options={
                'verbose_name': 'Товар условия промо',
                'verbose_name_plural': 'Товары условия промо',
            },
        ),
        migrations.CreateModel(
            name='PromoGiftProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество в подарок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_gifts', to='catalog.product', verbose_name='Подарок')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_products', to='catalog.promoaction', verbose_name='Промо акция')),
            ],
            options={
                'verbose_name': 'Подарок промо',
                'verbose_name_plural': 'Подарки промо',
            },
        ),
        migrations.AddConstraint(
            model_name='promoactionproduct',
            constraint=models.UniqueConstraint(fields=('promo', 'product'), name='unique_promo_condition_product'),
        ),
        migrations.AddConstraint(
            model_name='promogiftproduct',
            constraint=models.UniqueConstraint(fields=('promo', 'product'), name='unique_promo_gift_product'),
        ),
    ]
