# Generated by Django 5.0.10 on 2026-08-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_promoaction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoaction',
            name='promo_type',
        ),
        migrations.AddField(
            model_name='promoaction',
            name='condition_type',
            field=models.CharField(choices=[('fixed_set', 'Фиксированный состав'), ('total_quantity', 'Количество товаров из списка'), ('total_amount', 'Сумма товаров из списка')], db_index=True, default='fixed_set', max_length=30, verbose_name='Условие выполнения'),
        ),
        migrations.AddField(
            model_name='promoaction',
            name='reward_type',
            field=models.CharField(choices=[('gift', 'Подарок'), ('discount', 'Скидка')], db_index=True, default='gift', max_length=20, verbose_name='Результат акции'),
        ),
        migrations.AddField(
            model_name='promoaction',
            name='threshold_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Используется для условия «Сумма товаров из списка». Сумма рассчитывается по базовым ценам до применения скидок.', max_digits=14, null=True, verbose_name='Минимальная сумма, руб.'),
        ),
        migrations.AddField(
            model_name='promoaction',
            name='threshold_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Используется для условия «Количество товаров из списка».', null=True, verbose_name='Минимальное количество товаров'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Используется, если результат акции — скидка. Применяется только к товарам акции и не суммируется со скидкой клиента.', max_digits=5, null=True, verbose_name='Промо-скидка, %'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='image',
            field=models.ImageField(blank=True, help_text='Основное изображение, отображаемое на карточке акции.', null=True, upload_to='promo/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='short_description',
            field=models.CharField(blank=True, help_text='Отображается непосредственно на карточке акции.', max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='show_progress',
            field=models.BooleanField(default=False, help_text='Если включено, клиент увидит, сколько товаров или какой суммы не хватает до выполнения условий акции.', verbose_name='Показывать прогресс выполнения'),
        ),
        migrations.AlterField(
            model_name='promoactionproduct',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Указывается только для акции с фиксированным составом. Для условий по общему количеству или сумме оставьте поле пустым.', null=True, verbose_name='Необходимое количество'),
        ),
    ]
