# Generated by Django 5.0.10 on 2026-08-25 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_promoaction_promo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoaction',
            name='progress_threshold_percent',
            field=models.PositiveSmallIntegerField(default=50, help_text='Используется только если включено «Показывать прогресс выполнения». Например, 50 означает, что подсказка появится после выполнения 50% условий акции.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Показывать прогресс начиная с, %'),
        ),
        migrations.AlterField(
            model_name='promoaction',
            name='promo_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор акции'),
        ),
    ]
