# Generated by Django 5.0.10 on 2026-08-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_promoaction_progress_threshold_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Идентификатор подразделения')),
                ('name', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('min_delivery_amount', models.DecimalField(decimal_places=2, default=0, help_text='При меньшей сумме заказа клиенту будет доступен только самовывоз.', max_digits=12, verbose_name='Минимальная сумма для доставки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Идентификатор менеджера')),
                ('name', models.CharField(max_length=255, verbose_name='Менеджер')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('bitrix_id', models.CharField(blank=True, max_length=100, verbose_name='ID пользователя Bitrix24')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='catalog.department', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'ordering': ['name'],
            },
        ),
    ]
