# Generated by Django 5.0.10 on 2026-08-27 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='catalog.manager', verbose_name='Менеджер'),
        ),
    ]
