# Generated by Django 5.0.10 on 2026-09-18 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_contract_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('agreement_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Идентификатор соглашения в 1С')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование')),
                ('is_typical', models.BooleanField(db_index=True, default=False, verbose_name='Типовое')),
                ('counterparty_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Контрагент в 1С')),
                ('partner_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Партнер в 1С')),
                ('organization_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Организация в 1С')),
                ('price_type_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Вид цен в 1С')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Статус')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Согласовано')),
                ('operation', models.CharField(blank=True, max_length=100, verbose_name='Хозяйственная операция')),
                ('price_includes_vat', models.BooleanField(default=False, verbose_name='Цена включает НДС')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Соглашение с клиентом',
                'verbose_name_plural': 'Соглашения с клиентами',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='legalentity',
            name='partner_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Идентификатор партнера в 1С'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='price_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='catalog.pricetype', verbose_name='Актуальный тип цен'),
        ),
        migrations.AddField(
            model_name='contract',
            name='agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='catalog.agreement', verbose_name='Соглашение'),
        ),
    ]
