# Generated by Django 5.0.10 on 2026-06-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20241216_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('Number', models.IntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('holding', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('shipping_date', models.DateField()),
                ('shipping_type', models.CharField(max_length=100)),
                ('product_list', models.JSONField()),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='holding_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
