# Generated by Django 5.0.10 on 2026-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_ordermodel_alter_userprofile_holding_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
