# Generated by Django 5.0.10 on 2026-08-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_userprofile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
